<?php

namespace AppBundle\Repository;

/**
 * ComprobanteXEmpresaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComprobanteXEmpresaRepository extends \Doctrine\ORM\EntityRepository
{
}
