<?php

namespace AppBundle\Repository;

/**
 * GuiaRemisionDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuiaRemisionDetalleRepository extends \Doctrine\ORM\EntityRepository
{
}
