<?php

namespace AppBundle\Repository;

/**
 * NotaCreditoCompraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotaCreditoCompraRepository extends \Doctrine\ORM\EntityRepository
{
}
