<?php

namespace AppBundle\Repository;

/**
 * PedidoVentaEntregaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedidoVentaEntregaRepository extends \Doctrine\ORM\EntityRepository
{
}
