<?php

namespace AppBundle\Repository;

/**
 * PedidoVentaDetalleEntregaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedidoVentaDetalleEntregaRepository extends \Doctrine\ORM\EntityRepository
{
}
