<?php

namespace AppBundle\Repository;

/**
 * ProductoXPrecioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoXPrecioRepository extends \Doctrine\ORM\EntityRepository
{
}
